# Autogenerated wrapper script for nghttp3_jll for armv7l-linux-musleabihf
export libnghttp3

JLLWrappers.@generate_wrapper_header("nghttp3")
JLLWrappers.@declare_library_product(libnghttp3, "libnghttp3.so.0")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libnghttp3,
        "lib/libnghttp3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
